services:
  - type: web
    name: baccarat-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
      - key: COMPTEUR2_ACTIVE
        value: "true"
      - key: COMPTEUR2_B
        value: "5"
      - key: COMPTEUR3_ACTIVE
        value: "true"
      - key: COMPTEUR3_B
        value: "5"
      - key: COMPTEUR1_ACTIVE
        value: "true"
      - key: COMPTEUR1_B
        value: "8"
      - key: API_POLL_INTERVAL
        value: "5"
